### ISSUE TITLE
Can you replace the text with the application icon

### ISSUE THREAD

**Issue by QiangF** [aroma1994/polybar-windows#1]

**Comment by aroma1994** [comment]
Hello, QiangF.

As I understand you can use only font symbols in Polybar output. If that's true you anyway can't use existing application icons. But you may work and add your own masks to window names for your frequently used applications to have something like [https://fontawesome.com/icons/chrome](https://fontawesome.com/icons/chrome) instead of 'chromium' word as example.

**Comment by QiangF** [comment]
Thank you! 
Looks like this package is doing exactly like what you suggested.
https://github.com/SleepyBag/polybar-i3-workspace-windows
I am currently using tint2, it only support showing icon from _NET_WM_ICON property. Tint2 looks much more polished.
